model_names:
  large: openai/whisper-large-v2
  medium: openai/whisper-medium
  base: openai/whisper-base
processing:
  sampling_rate: 16000
  chunk_size: 2
  batch_size: 30
supported_media_formats:
  video:
    - .mp4
    - .avi
    - .webm
  audio:
    - .wav
    - .mp3
supported_languages:
  - english
  - chinese
  - german
  - spanish
  - russian
  - korean
  - french
  - japanese
  - portuguese
  - turkish
  - polish
  - catalan
  - dutch
  - arabic
  - swedish
  - italian
  - indonesian
  - hindi
  - finnish
  - vietnamese
  - hebrew
  - ukrainian
  - greek
  - malay
  - czech
  - romanian
  - danish
  - hungarian
  - tamil
  - norwegian
  - thai
  - urdu
  - croatian
  - bulgarian
  - lithuanian
  - latin
  - maori
  - malayalam
  - welsh
  - slovak
  - telugu
  - persian
  - latvian
  - bengali
  - serbian
  - azerbaijani
  - slovenian
  - kannada
  - estonian
  - macedonian
  - breton
  - basque
  - icelandic
  - armenian
  - nepali
  - mongolian
  - bosnian
  - kazakh
  - albanian
  - swahili
  - galician
  - marathi
  - punjabi
  - sinhala
  - khmer
  - shona
  - yoruba
  - somali
  - afrikaans
  - occitan
  - georgian
  - belarusian
  - tajik
  - sindhi
  - gujarati
  - amharic
  - yiddish
  - lao
  - uzbek
  - faroese
  - creole
  - pashto
  - turkmen
  - nynorsk
  - maltese
  - sanskrit
  - luxembourgish
  - myanmar
  - tibetan
  - tagalog
  - malagasy
  - assamese
  - tatar
  - hawaiian
  - lingala
  - hausa
  - bashkir
  - javanese
  - sundanese